name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Installing global Packages
      run: npm i -g gh-pages
    - name: Deploy to GH Pages
      run: |
        git config --global user.email ${{secrets.ANU_EMAIL}}
        git config --global user.name ${{secrets.ANU_USER_NAME}}
        git remote set-url origin https://${{secrets.PERSONAL_WEATHER_TOKEN}}@github.com/${{secrets.ANU_USER_NAME}}/weather-dashboard.git
        npm run deploy